#!/bin/bash
# Usage: help.sh
# Lists all available multi-agent scripts

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "Multi-Agent Collaboration Scripts"
echo "=================================="
echo ""
echo "Chat:"
echo "  send.sh \"msg\"     Send a message to chat"
echo "  history.sh        Show chat history"
echo "  watch.sh          Follow chat in real-time"
echo "  who.sh            List chat participants"
echo "  clear.sh          Clear chat (--archive to backup first)"
echo ""
echo "Identity:"
echo "  whoami.sh         Show your current identity"
echo ""
echo "Coordination:"
echo "  status.sh         Track file edits (set/clear/list/check)"
echo "  ping.sh           Ping other agents (broadcast or pane)"
echo "  task.sh           Lightweight task board (add/claim/done/list)"
echo ""
echo "Tmux Session:"
echo "  session.sh        Manage session (create/join/list)"
echo "  capture.sh N      Read pane N's output"
echo "  focus.sh N        Switch to pane N"
echo "  prompt.sh N msg   Send input to pane N"
echo "  kill.sh N         Kill pane N"
echo ""
echo "Startup:"
echo "  start.sh N \"prompt\"  Spawn N agents with prompt"
echo ""
echo "Run any script with --help for details."
